query GetEvents($input: QueryFilterDto!) {
  getEvents(input: $input) {
    items {
      createdAt
      description
      eventFormat
      eventType {
        id
        name
      }
      id
      img
      isTemplate
      name
      rental {
        id
        rentalEndTime
        rentalStartTime
        totalPrice
        user {
          avatar
          createdAt
          dob
          email
          firstName
          gender
          id
          lastName
          phoneNumber
          role {
            id
            name
          }
          roleId
          updatedAt
        }
      }
    }
    meta {
      currentPage
      itemCount
      itemsPerPage
      totalItems
      totalPages
    }
  }
}